[package]
name = "derive_deref"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Derive the Deref and DerefMut traits"
repository = "https://github.com/Ike-l/derive_deref"
readme = "README.md"

[dependencies]
quote = "1.0.36"
syn = "2.0.72"

[lib]
proc-macro = true